general:
  seed: 34
  seed_workers: true
trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: auto
  strategy: auto
  devices: auto
  logger:
    _target_: lightning.pytorch.loggers.WandbLogger
    project: worm-seq
    name: Base-Transformer
    log_model: True
  callbacks:
    - _target_: lightning.pytorch.callbacks.LearningRateMonitor
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      monitor: Val/Loss
      mode: min
      save_last: true
      save_top_k: 1
      every_n_epochs: 1
  max_epochs: 250
  log_every_n_steps: 10
  benchmark: false
  deterministic: true
  enable_progress_bar: true
  enable_model_summary: true
  sync_batchnorm: false
data:
  _target_: datasets.worm_dataloader.WormDataLoader
  train_dataset_path: #PATH_TO_IMG_PT
  val_dataset_path: #PATH_TO_IMG_PT
  test_dataset_path: #PATH_TO_IMG_PT

  train_rotation_path: #PATH_TO_ROTATION_CSV
  val_rotation_path: #PATH_TO_ROTATION_CSV
  test_rotation_path: #PATH_TO_ROTATION_CSV

  train_meta_data_path: #PATH_TO_METADATA_TSV
  val_meta_data_path: #PATH_TO_METADATA_TSV
  test_meta_data_path: #PATH_TO_METADATA_TSV

  train_tierpsy_feat_path: #PATH_TO_FEAT_TSV
  val_tierpsy_feat_path: #PATH_TO_FEAT_TSV
  test_tierpsy_feat_path: #PATH_TO_FEAT_TSV
  shuffle: true
  drop_last: true
  num_workers: 10
  pin_memory: true
  batch_size: 128
  img_size: 128
  seq_length: 12
  step: 5
  persistent_workers: false
  dataset_mean: [ 0.469818919369028, 0.469818919369028, 0.469818919369028 ]
  dataset_std: [ 0.09742516302252072, 0.09742516302252072, 0.09742516302252072 ]
  enc_rotation: ${model.enc_rotation}
  id_stepping: single # controls if overlapping sequences to be used
model:
  _target_: models.seq_transformer.transformer.TransformerPredictor
  input_dim: 64
  model_dim: 128
  num_heads: 2
  num_layers: 1
  dropout: 0.1
  input_dropout: 0.0
  lr: 5e-4
  warmup: 100
  max_iters: 47480
  image_encoder_module: models.encoder.vicreg_res18
  image_encoder_class: VICReg
  encoder_checkpoint: #PATH_TO_POSE_CHECKPOINT
  dataset_mean: ${data.dataset_mean}
  dataset_std: ${data.dataset_std}
  seq_length: ${data.seq_length}
  random_masking: false # this will overwrite mask_pos
  random_masking_per_forward: false
  mask_perc: 60
  mask_pos: [ 7, 8, 9, 10, 11 ]
  loss_type: "MSE"
  imp_factor: 1
  enc_rotation: True
